# Generated by Django 4.1 on 2022-08-28 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('INFO', 'Informática'), ('GAME', 'Games'), ('ESPO', 'Esporte'), ('MODA', 'Moda'), ('BELE', 'Beleza')], default=0, max_length=50)),
                ('preco', models.CharField(max_length=70)),
                ('descricao', models.CharField(max_length=70)),
                ('data_criacao', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
