from django.db import models
from django.utils.translation import gettext_lazy as _

class Estados(models.TextChoices):
    ACRE = 'AC', _('Acre')
    ALAGOAS = 'AL', _('Alagoas')
    AMAPA = 'AP', _('Amapá')
    AMAZONAS = 'AM', _('Amazonas')
    BAHIA = 'BA', _('Bahia')
    CEARA = 'CE', _('Ceará')
    DISTRITO = 'DF', _('Distrito Federal')
    ESPIRITO = 'ES', _('Espírito Santo')
    GOIAIS = 'GO', _('Goiás')
    MARANHAO = 'MA', _('Maranhão')
    MATO = 'MT', _('Mato Grosso')
    MATOSUL = 'MS', _('Mato Grosso do SuL')
    MINAS = 'MG', _('Minas Gerais')
    PARA = 'PA', _('Pará')
    PARAIBA = 'PB', _('Paraíba')
    PARANA = 'PR', _('Paraná')
    PERNAMBUCO = 'PE', _('Pernambuco')
    PIAUI = 'PI', _('Piauí')
    RIO = 'RJ', _('Rio de Janeiro')
    RIONORTE = 'RN', _('Rio Grande do Norte')
    RIOSUL = 'RS', _('Rio Grande do Sul')
    RONDONIA = 'RO', _('Rondônia')
    RORAIMA = 'RR', _('Roraima')
    SANTA = 'SC', _('Santa Catarina')
    SAO = 'SP', _('São Paulo')
    SERGIPE = 'SE', _('Sergipe')
    TOCANTINS = 'TO8', _('Tocantins')
