# Generated by Django 4.1.2 on 2022-10-10 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('corpo_mensagem', models.CharField(max_length=126)),
                ('icon', models.ImageField(blank=True, upload_to='foto-mensagem')),
                ('data_criacao', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
