# Generated by Django 4.1.2 on 2022-10-10 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_mensagens_publicada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensagens',
            old_name='publicada',
            new_name='habilitada',
        ),
    ]
